sonar.projectKey=healthcare-devsecops
sonar.projectName=Healthcare DevSecOps Demo
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=app/tests
sonar.language=py
sonar.python.version=3.11
sonar.qualitygate.wait=true
