apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: healthcare-network-policy
  namespace: healthcare
spec:
  podSelector:
    matchLabels:
      app: healthcare-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 5000
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
